# Generated by Django 6.1 on 2026-08-19 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_slug', models.SlugField(blank=True)),
                ('plivo_call_uuid', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In progress'), ('booked', 'Booked'), ('failed', 'Failed'), ('ended', 'Ended')], default='queued', max_length=20)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('last_agent_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='bookings.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
