# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


def backfill_staff_venues(apps, schema_editor):
    FacilityManager = apps.get_model("attendance", "FacilityManager")
    StaffVenue = apps.get_model("attendance", "StaffVenue")
    for staff in FacilityManager.objects.all():
        StaffVenue.objects.get_or_create(
            staff=staff,
            sport_id=staff.sport_id,
            defaults={"is_default": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("bookings", "0002_callsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitymanager",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("coach", "Coach"),
                ],
                default="manager",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="court_label",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="student",
            name="membership_tier",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("walkin", "Walk-in"),
                ],
                default="monthly",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="monthly_fee_paise",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="source",
            field=models.CharField(
                choices=[("staff", "Staff"), ("coach", "Coach")],
                default="staff",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="StaffVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_links",
                        to="bookings.sport",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="attendance.facilitymanager",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="staffvenue",
            constraint=models.UniqueConstraint(
                fields=("staff", "sport"), name="unique_staff_venue"
            ),
        ),
        migrations.CreateModel(
            name="CoachAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(max_length=12)),
                ("court_label", models.CharField(blank=True, max_length=40)),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.sport",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="attendance.facilitymanager",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="coachassignment",
            constraint=models.UniqueConstraint(
                fields=("staff", "sport", "session", "court_label"),
                name="unique_coach_assignment",
            ),
        ),
        migrations.CreateModel(
            name="CoachAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("session", models.CharField(max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        max_length=10,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now=True)),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.sport",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="attendance.facilitymanager",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="coachattendance",
            constraint=models.UniqueConstraint(
                fields=("staff", "date", "session"),
                name="unique_coach_checkin",
            ),
        ),
        migrations.RunPython(backfill_staff_venues, migrations.RunPython.noop),
    ]
